version: 2

models:

  - name: dim_host
    description: Host dimension table

    columns:
      - name: host_id
        tests:
          - unique
          - not_null


  - name: dim_listings
    description: Listing dimension table

    columns:
      - name: listing_id
        tests:
          - unique
          - not_null


  - name: fact_bookings
    description: Booking fact table

    columns:
      - name: booking_id
        tests:
          - unique
          - not_null

      