version: 2

models:
  - name: dim_host
    description: Host dimension table for analytics

    columns:
      - name: host_id
        description: Unique host identifier
        tests:
          - unique
          

  - name: fact_bookings
    description: Booking transaction fact table

    columns:
      - name: booking_id
        tests:
          - unique
         