version: 2

models:
  - name: s_host
    description: Cleaned host data from bronze layer

    columns:
      - name: host_id
        description: Unique identifier for host
        tests:
          - unique
          - not_null

      - name: host_name
        description: Name of host
        tests:
          - not_null

      - name: response_rate
        description: Host response percentage
