version: 2
models:

  - name: s_host
    description: Cleaned host data

    columns:
      - name: host_id
        tests:
          - unique
          - not_null

      - name: host_name
        tests:
          - not_null


  - name: s_listings
    description: Cleaned listing data

    columns:
      - name: listing_id
        tests:
          - unique
          - not_null

      - name: host_id
        tests:
          - not_null


  - name: s_bookings
    description: Cleaned booking data

    columns:
      - name: booking_id
        tests:
          - unique
          - not_null

      - name: listing_id
        tests:
          - not_null


